# Generated by Django 5.2.8 on 2026-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_modernize_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounts_tr_account_ef2c51_idx',
            old_name='accounts_tr_account_d3a1c2_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounts_tr_type_877a85_idx',
            old_name='accounts_tr_type_5b9f6a_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
