# Generated by Django 5.2.8 on 2026-05-15 18:07

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=128, unique=True)),
                ('access_token', accounts.fields.EncryptedTextField()),
                ('institution_id', models.CharField(blank=True, max_length=64)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('transactions_cursor', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('login_required', 'Re-authentication required'), ('error', 'Error')], default='active', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mask',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_account_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('plaid_transaction_id', ''), _negated=True), fields=('plaid_transaction_id',), name='uniq_plaid_txn'),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.plaiditem'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('plaid_item__isnull', False)), fields=('plaid_item', 'plaid_account_id'), name='uniq_plaid_account'),
        ),
    ]
