# Generated by Django 5.2.8 on 2026-05-15 21:58

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_plaiditem_account_last_synced_at_account_mask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('app_password', accounts.fields.EncryptedTextField()),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=128)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('folder', models.CharField(default='INBOX', max_length=64)),
                ('sender_filter', models.CharField(default='ubl.com.pk', max_length=128)),
                ('last_seen_uid', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('auth_error', 'Authentication failed'), ('error', 'Error')], default='active', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('email_message_id', ''), _negated=True), fields=('email_message_id',), name='uniq_email_msg'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_inboxes', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_inboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='emailinbox',
            constraint=models.UniqueConstraint(fields=('user', 'email_address'), name='uniq_user_inbox'),
        ),
    ]
