# Generated by Django 5.2.8 on 2026-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailinbox_transaction_email_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinbox',
            name='sender_filter',
            field=models.CharField(default='admin.ebanking@ubl.com.pk', max_length=128),
        ),
    ]
