# Generated by Django 5.2.8 on 2026-05-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_emailinbox_sender_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
    ]
