# Generated by Django 5.2.8 on 2026-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reported_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
